[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/deer/*"
  to = "/deer/index.html"
  status = 200

[[redirects]]
  from = "/git/*"
  to = "/git/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/deer/index.html"
  status = 302
